language: python

python:
- 2.7
- 3.4
- 3.5

before_install:
- git clone https://github.com/ericdill/ci ~/scripts

install:
- . ~/scripts/install-miniconda.sh
- conda install python=$TRAVIS_PYTHON_VERSION pip
- pip install -r test-requirements.txt
- pip install -e .

script:
- kernda -h
- pytest
